# fly.toml app configuration file generated for resume-api-express on 2023-11-03T12:33:15-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "resume-api-express"
primary_region = "den"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
